version: '3.8'

services:
  frontend:
    build:
      context: ./herb-tracker-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./herb-tracker-backend
    ports:
      - "3001:3001"
    environment:
      # Use host.docker.internal to connect to the Hardhat node running on the host
      RPC_URL: http://host.docker.internal:8545
    # 'host.docker.internal' is added to the container's /etc/hosts file
    # This is required for Docker on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
